export interface Product {
    id: number;
    name: string;
    category: 'candles' | 'accessories';
    price: number;
    priceFormatted: string;
    description: string;
    image: string;
    rating: number;
    reviews: number;
    features: string[];
    details: string;
    customizable: boolean; // Cờ đánh dấu sản phẩm có thể tùy chỉnh (Nến) hay không (Phụ kiện)
}

export const products = [
    // --- NẾN THƠM (CUSTOMIZABLE = TRUE) ---

    {
        id: 1,
        name: 'Nến thơm Hoa Nhài',
        category: 'candles',
        price: 299000,
        priceFormatted: '299.000 đ',
        description: 'Mùi hoa nhài tươi, ngọt nhẹ, giống trà hoa nhài mới pha',
        image: '/products/Hoa lài.webp',
        customizable: true,
    },
    {
        id: 2,
        name: 'Nến thơm Thảo Mộc',
        category: 'candles',
        price: 299000,
        priceFormatted: '299.000 đ',
        description: 'Mùi lá xanh tươi, hơi cay nhẹ như húng, rosemary; cảm giác sạch và mát',
        image: '/products/Thảo mộc.webp',
        customizable: true,
    },
    {
        id: 3,
        name: 'Nến thơm Vani',
        category: 'candles',
        price: 399000,
        priceFormatted: '399.000 đ',
        description: 'Mùi vani ngọt ấm, giống bánh nướng hoặc kem vani',
        image: '/products/Vani.webp',
        customizable: true,
    },
    {
        id: 4,
        name: 'Nến thơm Cam Chanh',
        category: 'candles',
        price: 349000,
        priceFormatted: '349.000 đ',
        description: 'Mùi vỏ cam, chanh tươi; chua ngọt, rất sảng khoái',
        image: '/products/Cam chanh.webp',
        customizable: true,
    },
    {
        id: 5,
        name: 'Nến thơm Oải Hương',
        category: 'candles',
        price: 349000,
        priceFormatted: '349.000 đ',
        description: 'Mùi hoa khô nhẹ, giống tinh dầu spa; dịu và dễ chịu',
        image: '/products/Oải hương.webp',
        customizable: true,
    },
    {
        id: 6,
        name: 'Nến thơm Biển Cả',
        category: 'candles',
        price: 349000,
        priceFormatted: '349.000 đ',
        description: 'Mùi gió biển mát, hơi mặn và sảng khoái, giống không khí gần biển',
        image: '/products/Biển cả.webp',
        customizable: true,
    },

    {
        id: 7,
        name: 'Hộp diêm đốt nến thơm',
        category: 'accessories',
        price: 20000,
        priceFormatted: '20.000 đ',
        description: 'Hộp diêm chuyên dụng dài 10cm, giúp thắp nến an toàn và dễ dàng.',
        image: '/phu-kien/hop-diem.webp',
        rating: 4.9,
        reviews: 340,
        features: ['Que diêm dài 10cm', 'Gỗ tự nhiên', 'Đầu diêm dễ bắt lửa', 'Hộp đựng vintage'],
        details: 'Hộp diêm Préci được thiết kế chuyên dụng cho nến thơm. Với chiều dài vượt trội, bạn có thể dễ dàng thắp nến khi sáp đã vơi đi mà không sợ bỏng tay.',
        customizable: false,
    },
    {
        id: 8,
        name: 'Chuông chụp tắt nến',
        category: 'accessories',
        price: 90000,
        priceFormatted: '90.000 đ',
        description: 'Dụng cụ tắt nến chuyên nghiệp, ngăn khói đen và giữ mùi hương.',
        image: '/phu-kien/chuong-chup.webp',
        rating: 4.8,
        reviews: 156,
        features: ['Chất liệu thép không gỉ', 'Mạ vàng/bạc sang trọng', 'Ngăn khói đen', 'Tay cầm dài an toàn'],
        details: 'Sử dụng chuông chụp là cách tắt nến văn minh nhất. Nó giúp dập tắt ngọn lửa ngay lập tức mà không tạo ra khói đen ám mùi khét, giữ trọn vẹn hương thơm của nến.',
        customizable: false,
    },
    {
        id: 9,
        name: 'Đế gỗ thông đựng nến',
        category: 'accessories',
        price: 15000,
        priceFormatted: '15.000 đ',
        description: 'Đế lót nến bằng gỗ thông tự nhiên, phong cách mộc mạc.',
        image: '/phu-kien/de-go-thong.webp',
        rating: 4.7,
        reviews: 210,
        features: ['Gỗ thông nguyên khối', 'Vân gỗ tự nhiên', 'Chống nóng mặt bàn', 'Decor đẹp mắt'],
        details: 'Đế gỗ thông lát tròn mang lại vẻ đẹp mộc mạc, tự nhiên cho hũ nến. Ngoài tác dụng trang trí, nó còn giúp cách nhiệt, bảo vệ bề mặt bàn của bạn.',
        customizable: false,
    },
    {
        id: 10,
        name: 'Khay đựng nến kim loại',
        category: 'accessories',
        price: 60000,
        priceFormatted: '60.000 đ',
        description: 'Khay kim loại sáng bóng, tôn lên vẻ sang trọng cho hũ nến.',
        image: '/phu-kien/khay-kim-loai.webp',
        rating: 4.8,
        reviews: 89,
        features: ['Kim loại mạ cao cấp', 'Bề mặt sáng bóng', 'Dễ dàng vệ sinh', 'Phong cách hiện đại'],
        details: 'Chiếc khay kim loại hình oval là điểm nhấn hoàn hảo cho góc nến của bạn. Phản chiếu ánh lửa lung linh và bảo vệ không gian khỏi sáp nến rơi vãi.',
        customizable: false,
    },
    {
        id: 11,
        name: 'Kéo cắt bấc nến',
        category: 'accessories',
        price: 80000,
        priceFormatted: '80.000 đ',
        description: 'Dụng cụ không thể thiếu để duy trì ngọn lửa nến đẹp và sạch.',
        image: '/phu-kien/keo-cat-bac-nen.webp',
        rating: 5.0,
        reviews: 112,
        features: ['Lưỡi cắt sắc bén', 'Thiết kế cong chuyên dụng', 'Hứng vụn bấc', 'Thép không gỉ'],
        details: 'Để nến cháy đều và không có khói đen, bấc nến cần được cắt ngắn còn 0.5cm trước mỗi lần đốt. Kéo cắt bấc chuyên dụng giúp bạn thao tác dễ dàng ngay cả khi nến nằm sâu trong hũ.',
        customizable: false,
    },
    {
        id: 12,
        name: 'Chóng chóng khuếch tán',
        category: 'accessories',
        price: 100000,
        priceFormatted: '100.000 đ',
        description: 'Quay đều khi thắp nến, tạo hiệu ứng ánh sáng lung linh.',
        image: '/phu-kien/chong-chong.webp',
        rating: 4.9,
        reviews: 75,
        features: ['Tự động quay nhờ nhiệt', 'Kim loại mạ vàng', 'Hiệu ứng lung linh', 'Khuếch tán hương tốt hơn'],
        details: 'Chong chóng xoay là món phụ kiện "ma thuật". Nhiệt lượng từ ngọn nến sẽ làm cánh quạt quay đều, phản chiếu ánh sáng lấp lánh khắp căn phòng.',
        customizable: false,
    },
    {
        id: 13,
        name: 'Quế khô trang trí nến',
        category: 'accessories',
        price: 40000,
        priceFormatted: '40.000 đ',
        description: 'Thanh quế tự nhiên, dùng để decor và tạo hương thơm ấm áp.',
        image: '/phu-kien/que-kho.webp',
        rating: 4.6,
        reviews: 45,
        features: ['Quế thanh tự nhiên', 'Mùi hương ấm áp', 'Dùng decor nến/quà', 'Thân thiện môi trường'],
        details: 'Những thanh quế khô mộc mạc không chỉ dùng để trang trí quanh hũ nến mà còn tỏa ra hương thơm gỗ ấm áp, dễ chịu khi để gần nguồn nhiệt.',
        customizable: false,
    },
    {
        id: 14,
        name: 'Combo chăm sóc nến',
        category: 'accessories',
        price: 299000,
        priceFormatted: '299.000 đ',
        description: 'Bộ 3 món (Kéo, Chuông, Khay) hoàn hảo cho người chơi nến.',
        image: '/phu-kien/combo.webp',
        rating: 5.0,
        reviews: 28,
        features: ['Tiết kiệm hơn mua lẻ', 'Đầy đủ dụng cụ', 'Hộp quà sang trọng', 'Món quà lý tưởng'],
        details: 'Combo bao gồm: 1 Kéo cắt bấc, 1 Chuông tắt nến và 1 Khay đựng. Đây là bộ starter-kit hoàn hảo cho bất kỳ ai bắt đầu đam mê bộ môn nến thơm.',
        customizable: false,
    },
]

export const getProductById = (id: number) => products.find(p => p.id === id);